import{a as L,i,S as b}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const v="50608541-859a2339eccb527f555031f69",w="https://pixabay.com/api/";async function p(s,t=1,n=15){const o={key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n};return(await L.get(w,{params:o})).data}function g(s){return s.map(({webformatURL:t,largeImageURL:n,tags:o,likes:e,views:r,comments:c,downloads:y})=>`
    <li class="photo-card">
      <a class="gallery__link" href="${n}">
        <img src="${t}" alt="${o}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${e}</p>
        <p><b>Views:</b> ${r}</p>
        <p><b>Comments:</b> ${c}</p>
        <p><b>Downloads:</b> ${y}</p>
      </div>
    </li>
  `).join("")}const S=document.querySelector("#search-form"),m=document.querySelector(".gallery"),l=document.querySelector(".load-more"),d=document.querySelector(".loader");let h="",a=1,u=0,f;S.addEventListener("submit",async s=>{if(s.preventDefault(),m.innerHTML="",l.classList.add("hidden"),d.classList.remove("hidden"),a=1,h=s.target.elements.searchQuery.value.trim(),!h){i.warning({message:"Please enter a search query!",position:"topRight"}),d.classList.add("hidden");return}try{const t=await p(h,a);if(u=t.totalHits,t.hits.length===0){i.info({message:"Sorry, no images match your search query. Try again!",position:"topRight"});return}m.innerHTML=g(t.hits),f=new b(".gallery a").refresh(),t.hits.length<15||a*15>=u?l.classList.add("hidden"):l.classList.remove("hidden"),i.success({message:`Found ${u} images.`,position:"topRight"})}catch(t){console.error(t),i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{d.classList.add("hidden")}});l.addEventListener("click",async()=>{a++,d.classList.remove("hidden");try{const s=await p(h,a);m.insertAdjacentHTML("beforeend",g(s.hits)),f.refresh();const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),a*15>=u&&(l.classList.add("hidden"),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(s){console.error(s),i.error({message:"Error while loading more images.",position:"topRight"})}finally{d.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
